### ISSUE TITLE
Did not find any Terraform files (*.tf) Error

### ISSUE THREAD

**Issue by jack-of-AllTrades** [gruntwork-io/terragrunt#1222]
I've recently upgraded terragrunt from version 0.23.7 to 0.23.27, with this upgrade seems like dependency block is broken. 

My dependency block is like:

```
dependency "vpc" {
  config_path = "../vpc"

  mock_outputs_allowed_terraform_commands = ["validate"]
  mock_outputs = {
    subnet_ids        = ["12323", "s432332f", "4365656"]
    asg_sec_group_ids = ["sg-45454", "sg-6677", "sg-8867"]
  }
}

dependency "iam" {
  config_path = "../../_global/iam"

  mock_outputs_allowed_terraform_commands = ["validate"]
  mock_outputs = {
    instance_profile_name = "ec2_instance_profile"
    pub_key_name          = "3453534543.pub"
  }
}

```

usually with version 0.23.7 when i run `terragrunt plan --terragrunt-source ../../modules//cluster` it works without any errors.

With the upgrade when i run the same command i see the following: 
Encountered the following errors:
Did not find any Terraform files (*.tf) in /Iac/gitlab.com/company/devops/modules.git/iam

when i checked the .terragrunt-cache dir it has hcl files along wth .terragrunt-module-manifest file

**Contents of .terrgarunt-module-manifest**
```
2��fileManifestEntry��Path
                          IsDir������/Users/jack/vpc/.terragrunt-cache/DK92S8IB_UqsPV0UlJMCXGfRH0A/G1SNNliYX3qhKcNQzSK2yFhNVa4/git@gitlab.com:/Iac/gitlab.com/company/devops/modules.git/iam/terragrunt.hcl%
```

- Not sure why it's using gitlab git dir and copies terragrunt file instead of modules folder with tf files. Although i used terragrunt source flag to use local dir instead of git dir for local testing

- I've tried running it plan-all to test multiple dependencies it still throws the same error

**Comment by brikis98** [comment]
I'm guessing it's due to the changes here: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.9. Could you take a look at those release notes and let us know if that helps?

**Comment by jack-of-AllTrades** [comment]
i've tried using both / and // and it still throws the same error with v0.23.27

```
terragrunt plan --terragrunt-source ../../modules//cluster
terragrunt plan --terragrunt-source ../../modules/cluster
```

**Comment by yorinasub17** [comment]
Is the `iam` module in a different repo than the cluster repo? E.g., is it at the path `../../modules//iam`?

The change in `v0.23.9` is that the `terragrunt-source` flag now updates all the sources, including the dependency block. E.g., if in your `iam` module `terragrunt.hcl` you had:

```hcl
terraform {
  source = "some-git-repo/modules//iam"
}
```

the `terragrunt-source` flag with the dependency will be the same as passing in `../../modules//iam` (as in, it replaces everything before `//` in the terraform source of `terragrunt.hcl` with whatever is before `//` in the option you pass in to `--terragrunt-source`).

**Comment by cedelis** [comment]
@jack-of-AllTrades ,

Have you figured out a work-around? I am experiencing the exact same issue. I had to go back to terragrunt v0.23.8 in order to get things working again.

**Comment by smeeklai** [comment]
I also experienced the same issue. But after I read @yorinasub17 explanation, I was able to solve after carefully checked the configuration. I'm using terragrunt version `v0.23.36`

Context: I cloned and re-created a new live repo from an existing live repo. As I copied from another live repo, all `terragrunt.hcl` files originally has `source` pointing to `git`.

Let's say I've Service `A` and `B`. Service `B` has service `A` as a dependency. When I ran `terragrunt` command in service `A` with `terragrunt-source` flag, everything works fine.

However, when I ran the same command in service `B`. I got the error `Did not find any Terraform files (*.tf) in ..../.terragrunt-cache/PATH_TO_SERVICE_A`. I checked the `PATH_TO_SERVICE_A` and found there was an additional unexpected sub-folder appended into it. After all the hassle, I was able to determine that the unexpected sub-folder was taken from the `git......//UNEXPECTED_FOLDER/SERVICE_B` in the `source` configured in service `A`. Just same as the explanation
>  it replaces everything before // in the terraform source of terragrunt.hcl with whatever is before // in the option you pass in to --terragrunt-source

There's no such `UNEXPECTED_FOLDER` sub-folder in the `terragrunt-source` I passed onto. Hence, it couldn't find any `*.tf` files so Terragrunt throw the error

**Comment by jack-of-AllTrades** [comment]
seems like the problem is resolved in v0.25.1

**Comment by thnee** [comment]
BTW this is the same error you get if you have a typo in the module path.

Terragrunt seems to create a directory in `.terragrunt-cache` for the incorrectly named module, and uses that as if it was a real module, but the directory is just empty. Would not hurt with some additional error handling here.

**Comment by brikis98** [comment]
> BTW this is the same error you get if you have a typo in the module path.
> 
> Would not hurt with some additional error handling here.

That's a very good point. Would you be up for a PR to improve that?

**Comment by patrickbeck1337** [comment]
Hey,
I am still experience this issue running `terragrunt run-all init` in a Github Actions pipeline. I am using terraform version `0.13.0` and terragrunt version `0.26.7`.

I have following project structure:
```
root
|─stage-A
   └─app1
          └─terragrunt.hcl
   └─app2
          └─terragrunt.hcl
   └─terragrunt.hcl
|─modules
   └─module-A
          └─main.tf
          └─...
   └─module-B
          └─main.tf
          └─...
   └─...
```

I am trying to run `terragrunt run-all init` in `root/stage-A`

app1 has for example the source attribute`source = "../../modules/module-A"` in the `root/stage-A/app1/terragrunt.hcl` file

Here is the error log of the GitHub Runner.

```
[terragrunt] 2022/06/23 10:40:57 Did not find any Terraform files (*.tf) in /home/runner/work/root/stage-A
[terragrunt] 2022/06/23 10:40:57 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
Maybe someone has a hint for me.
