### ISSUE TITLE
Terragrunt fails to get outputs of dependency

### ISSUE THREAD

**Issue by mkv-ts** [gruntwork-io/terragrunt#1330]
I get the following error when running "terragrunt apply" in module "bbb":

```
[terragrunt] 2020/09/08 19:46:04 /../aaa/terragrunt.hcl is a dependency of /.../bbb/terragrunt.hcl but detected no outputs. Either the target module has not been applied yet, or the module has no outputs. If this is expected, set the skip_outputs flag to true on the dependency block.
```

There is however outputs. My code worked with terragrunt 0.23.36, but broke with 0.23.37. It doesn't work with 0.24.0 either.
Using terragrunt version 0.13.2 during all runs.

The setup is as follows:
```
# module "aaa":
include {
  path = find_in_parent_folders()
}

# terragrunt.hcl in parent folder
dependency "bbb" {
  config_path = "/.../ccc")
}
```

**Comment by yorinasub17** [comment]
If you want to use relative paths, you need to remove the prefix `/`. Otherwise, that gets interpretted as an absolute path.

**Comment by mkv-ts** [comment]
No, it's not relative paths - it's three dots in the example above, not two. I just removed my long path since it's not relevant.

Ah, I see there was one with only two - I'll update the post!

**Comment by yorinasub17** [comment]
Ah gotcha. Sorry for the confusion.

Can you share how you are configuring your remote state? Does accessing the remote state depend on any special processing like `hooks` and `extra_arguments`, or getting plugins? If so, does it work if you set the `disable_dependency_optimization = true` flag?

See the docs on [dependency optimization](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependency) for more info.

**Comment by mkv-ts** [comment]
The dependency "bbb" is actually used to when I define the remote state...

This is from the included terragrunt.hcl:
```
remote_state {
  backend = "s3"

  config = {
    bucket         = dependency.bbb.outputs.s3_bucket_name
    dynamodb_table = dependency.bbb.outputs.dynamodb_name
    ...
  }
}
```

Will check the dependency opt tomorrow! Thanks!

**Comment by yorinasub17** [comment]
Oh hmm that should work automatically... I'll need to investigate this to see what might have caused the regression.

For now, disabling the optimization should work.

**Comment by mkv-ts** [comment]
I tried adding the "disable_dependency_optimization = false" to all remote_state -blocks, no change!

**Comment by yorinasub17** [comment]
I spent some time digging into this, but I was unable to reproduce the particular issue you are running into.

Can you take a look at my test module and see if you can identify some differences between your setup and mine? https://github.com/gruntwork-io/terragrunt/tree/yori-investigate-dependency-regression/test/fixture-get-output/nested-optimization-dependency

Note how I am using outputs from `deepdep` to feed into the remote state block for `dep`.

**Comment by mkv-ts** [comment]
I fixed a test case and invited you @yorinasub17 
I can't post this code in public...

**Comment by mkv-ts** [comment]
I was adding a docker image to the repo, to make sure we were running the same thing. But I couldn't recreate the issue in that new image (it still exists in our "real" docker image).

So this issue must be because of some other config we're doing somewhere... I will look into this further when I have time, and get back to you!

**Comment by brudnyhenry** [comment]
Hi,
Not sure what was the outcome of the investigation but I face the same issue.
The example structure I have looks like this
```bash
└── xxx

    ├── aks

    │   └── terragrunt.hcl

    └── aks-addon

        └── terragrunt.hcl

```
In my "aks-addon" module terragrunt.hcl I defined dependency
```hcl
dependency "aks" {
  config_path = "../aks"
}
```

But when I try to start any terragrunt command inside aks-addon directory I get

```bash
[terragrunt] [/home/adamplaczek/xxx/aks] 2020/11/26 08:16:35 Running command: terraform init -get=false -get-plugins=false

[terragrunt] [/home/adamplaczek/xxx/aks] 2020/11/26 08:16:38 Running command: terraform output -json

[terragrunt] 2020/11/26 08:16:40 /home/adamplaczek/xxx/aks/terragrunt.hcl is a dependency of /home/adamplaczek/xxx/aks-addons/terragrunt.hcl but detected no outputs. Either the target module has not been applied yet, or the module has no outputs. If this is expected, set the skip_outputs flag to true on the dependency block.
```
But when I enter the dependency manually and start 
```bash
terraform init -get=false -get-plugins=false
terraform output -json
```
I can see the output

**Comment by khushil** [comment]
Sadly I get the same problem but for me the` disable_dependency_optimization = true` doesn't fix. Basically I can't delete the alb because it can't get outputs of it's security group. So I'm left with a manual delete which is odd.

**Comment by khushil** [comment]
> As a side note, the dependency fetching will also naturally fail if you wipe the terragrunt cache, as terragrunt doesn't know to switch to that workspace when it reinitializes the cache. So if you are wiping the cache in between runs, that can also cause this issue.

I thought https://terragrunt.gruntwork.io/docs/features/caching/ meant we could safely get rid of these or are you talking about something else?

**Comment by JeremieCharest** [comment]
We triggered the issue when we migrated our remote state files (S3, Dynamo for locking) to another location. Before that, relative dependencies were working fine but now `plan` and `apply` are failing. Applying in the dependency folder generate outputs but the downstream module don't see them like it was used to do before.

The `disable_dependency_optimization = true` workaround unblocked us. We also tried to change relative path to absolute but it didn't helped.

terraform = 0.12.29
terragrunt = 0.26.2

**Comment by valdestron** [comment]
Still reproducing this with:
terraform 0.15.2
terragrunt 0.29.2

**Comment by czenker** [comment]
The issue occurred for us after updating from terraform `0.13` to `0.15` and terragrunt from `0.23` to `0.29`.

:point_right: We could **fix the issue** by deleting the `.terraform` directory in the dependend project. Now it works even without `disable_dependency_optimization = true`.

This might also explain why @yorinasub17 could not reproduce the issue.

**Comment by alxy** [comment]
I had the same issue and I had the following configuration that caused this bug for me:

```hcl
config = {
    key                  = "${path_relative_to_include()}/terraform.tfstate"
    resource_group_name  = get_env("REMOTE_STATE_RESOURCE_GROUP", "rg-terragrunt-backend-state")
    storage_account_name = get_env("REMOTE_STATE_STORAGE_ACCOUNT", "stterragruntstate")
    container_name       = get_env("REMOTE_STATE_STORAGE_CONTAINER", "terragrunt")
  }
```

This means, the backend configuration is dynamic and determined by environment variables. However, I needed to run terragrunt from an automation pipeline (in our case Azure pipelines), and then the same backend configuration is used for the modules **and all the dependencies**.
I think a better practice is to hardcode the configuration in `terragrunt.hcl` to seamlessly work with different state files for different modules:

```hcl
config = {
    key                  = "${path_relative_to_include()}/terraform.tfstate"
    resource_group_name  = "rg-terragrunt-backend-state"
    storage_account_name = "stterragruntstate"
    container_name       = "deployment-stamp-eu1-dev"
  }
```


Hope it helps if someone finds himself in the same situation.

**Comment by naul1** [comment]
Same issue as the original post:

TG = v0.29.10
TF = v1.0.0

**Comment by yorinasub17** [comment]
@naul1 FYI terragrunt does not yet officially support tf 1.0. Please follow https://github.com/gruntwork-io/terragrunt/issues/1710 for when we provide support.

**Comment by yorinasub17** [comment]
> I thought https://terragrunt.gruntwork.io/docs/features/caching/ meant we could safely get rid of these or are you talking about something else?

For others benefit, the reason the cache is no longer ephemeral if you are using workspaces is because the cache now contains environmental context (the enabled workspace) that is recorded on disk.

**Comment by yorinasub17** [comment]
@valdestron when you say

> My modules was in plan stage.

Do you mean the modules were in a clean slate with no deployed infrastructure? In that case the dependency fetching is properly giving you an error because there are no outputs (because the dependent module hasn't been applied) when your configuration expects it. Using `mock_outputs` to support `plan` is the proper solution for that.

**Comment by aalmazanarbs** [comment]
> @valdestron when you say
> 
> > My modules was in plan stage.
> 
> Do you mean the modules were in a clean slate with no deployed infrastructure? In that case the dependency fetching is properly giving you an error because there are no outputs (because the dependent module hasn't been applied) when your configuration expects it. Using `mock_outputs` to support `plan` is the proper solution for that.

Problem continues in 2022 latest version...

`mock_outputs` solution is very poor since `plan` tells one thing and `apply` does other. In addition, having production code with "mocks" is very "strange".

**Comment by ludichrislyts** [comment]
> In that case the dependency fetching is properly giving you an error because there are no outputs (because the dependent module hasn't been applied) when your configuration expects it.

This was the solution for me. I was trying to test changes to infrastructure using a custom prefix, and those resources did not exist in AWS. Running init and apply on the modules supplying the outputs for the dependent modules solved this issue.

**Comment by defyjoy** [comment]
Is there any movement to this ? This is a very peculiar case since this is a classic case of terraform plan and identifying dependencies. Mock is a way out though but it is a very misguiding in plan vs apply .

**Comment by camarrone** [comment]
Hello everyone.

I'm using the latest version (v0.38.7) and if I use `mock_outputs` terragrunt always uses the values from the `mock_outputs` and never detects the outputs from the dependecy, even if I set `skip_outputs = false`

Has anyone solved this?

Thanks.

**Comment by shbedev** [comment]
We experienced the same issue when importing resources into terragrunt.
Apparently, when running `terragrunt state pull` in the dependency path, we found that the "outputs" object was empty in the state. This can also be checked by running `terragrunt output`.
Running `terragrunt refresh` solves it!

**Comment by kenchan0130** [comment]
Even in my environment, running refresh like @shbedev 's method solved this problem.

However, if the terraform project is large, for example, with many dependencies, refresh is very slow.
Does anyone know how to optimize the execution speed by getting only the output?

**Comment by PassionateDeveloper86** [comment]
Have the same problem, tried everything but didnt get though it. For me it was a reason to not use terragrunt any more.

**Comment by ds-evo** [comment]
after `terragrunt run-all refresh` i could see the outputs (without mocking)

**Comment by SankethBK** [comment]
Getting same error, I am trying to run `terragrunt run-all init` in https://github.com/vallard/K8sClass/tree/master/terragrunt/stacks/stage using `terragrunt version v0.43.0` 

Full error 

`ERRO[0013] Module /Users/sanketh.bk/my_projects/k8s/eks/k8sclass/terragrunt/stacks/stage/eks has finished with an error: /Users/sanketh.bk/my_projects/k8s/eks/k8sclass/terragrunt/stacks/stage/vpc/terragrunt.hcl is a dependency of /Users/sanketh.bk/my_projects/k8s/eks/k8sclass/terragrunt/stacks/stage/eks/terragrunt.hcl but detected no outputs. Either the target module has not been applied yet, or the module has no outputs. If this is expected, set the skip_outputs flag to true on the dependency block.  prefix=[/Users/sanketh.bk/my_projects/k8s/eks/k8sclass/terragrunt/stacks/stage/eks] 
ERRO[0013] 1 error occurred:
        * /Users/sanketh.bk/my_projects/k8s/eks/k8sclass/terragrunt/stacks/stage/vpc/terragrunt.hcl is a dependency of /Users/sanketh.bk/my_projects/k8s/eks/k8sclass/terragrunt/stacks/stage/eks/terragrunt.hcl but detected no outputs. Either the target module has not been applied yet, or the module has no outputs. If this is expected, set the skip_outputs flag to true on the dependency block.`

**Comment by DanielViglione** [comment]
Surprising this error still persists after all this time. It is clear terragrunt is not production ready.

**Comment by DanielViglione** [comment]
Yeah this error still persists even after 2 years of the original post. To get this to work, unfortunately I had to generate the outputs directly in the CI/CD environment:

      - name: Check Account Outputs
        run: |
          cd modules/account-settings/infrastructure
          terraform init
          terraform refresh
          terraform output

And then after that, the dependency block is able to retrieve the outputs. It's a terrible hack, but it is clear the underlying issue here will not be resolved for some time.

**Comment by DanielViglione** [comment]
mock_outputs is also a terrible solution for this. The output of a plan using mock outputs does not reflect the actual real plan that should be, e.g. renaming resource app-test -> app-fake.

**Comment by DanielViglione** [comment]
There is also an issue with using mock_outputs. If you use mock_outputs, such as a vpc_id and the source module uses  a terraform data source, e.g:

```
data "aws_vpc" "selected" {
  id          = var.vpc_id
}
```

Then the plan will fail with "no matching vpc id" found, if you use a mock vpc id string, which by the name "mock_outputs" suggests you should be able to use mock strings.

**Comment by Thijmen** [comment]
Still happening to me on Terraform 1.3.7 (darwin_arm64) and Terragrunt v0.43.2

**Comment by aceqbaceq** [comment]
mocking variable is terrible solution

**Comment by corjanZee** [comment]
Why does it still try to reslove the inputs whilst the skip flag is set to true and skip_outputs is set to true

**Comment by baileyivancic** [comment]
Has there been any progress on this? This is currently blocking a refactor of our infrastructure, as it will not allow an `init` of modules which are new and have dependencies. As others have stated, using `mock_outputs` seems to be a very poor solution that introduces risk between `init/plan` and `apply`.

**Comment by snorrea** [comment]
I'm facing the same issue. My project will ditch Terragrunt and go for plain Terraform. For context, to try this out, we set up a simple example repo with literally two Azure resources, a resource group and a storage account, as two different modules with a dependency on the resource group from the storage account. While I was originally excited by the prospect of having less repeated code, when fundamental functionality like this isn't in place, what's even the point? None of the workarounds work for me.
Keeping my fingers crossed this gets picked up soon, meanwhile going WET...

**Comment by alxy** [comment]
@snorrea can you share the code of that Sample repository? From my experience terragrunt works very Well, and often Times it is really just a configuration issue.

**Comment by jvanenckevort** [comment]
I have worked with Terragrunt and Terraform for a long time. Because this issue hasn't been fixed for years, I am going to move on from Terragrunt. The positive effects of Terragrunt do not outweigh the negative side-effects, for example the flawed dependency resolution. But for larger projects, I have also noted that breaking the state up doesn't really benefit the build time in terms of caching and speed. And dividing the state in different substates was exactly one of the most valuable things Terragrunt had to offer.

The problem here is that when running a `terragrunt run-all plan`, newly added resources or newly added attributes (i.e. outputs) are not being resolved before terragrunt.hcl files that actually use those new attributes/modules as a dependency. This is probably a fundamental issue, hence why it hasn't been resolved yet. On the other hand, a plan on a submodule outputs newly added attributes, so why can other modules not wait before their dependencies are fully planned and outputs are known?

**Comment by hypervtechnics** [comment]
We experimented with examining the plan output and generatong local stubs in the terraform code using a special provider marking the corresponding variables of the outputs in the dependent module as not yet known during plan time.

This way you can still have a glance at the impact and have your changes plannable to some extent but of course with limitations. It has probably been mentioned a couple times before, but things are complex. What if e.g. you are using the kubernetes provider in the dependent module and configure it using a data block using the cluster name got from the first module? The cluster does not exist yet and the data will fail.

Terragrunt can not fix this. Instead the concept should be solved on a higher level in terraform itself. Tools like terragrunt help in splitting things up in an attempt to fix a flaw or unconsidered use case in the design of how terraform works...

**Comment by paololazzari** [comment]
I just ran into this, however there was an error on my part. This was my layout (gke module depends on vpc) that I had:

```
└── dev
│  ├── gke
│  │   └── terragrunt.hcl
│  │   └── cluster.tf
│  └── vpc
│      └── terragrunt.hcl
│      └── network.tf
└── modules
   └── gke
   │   └── main.tf
   │   └── variables.tf
   └── vpc
       └── main.tf
       └── outputs.tf
       └── variables.tf
```

```bash
$ terragrunt plan
ERRO[0002] /tmp/dev/vpc/terragrunt.hcl is a dependency of /tmp/dev/gke/terragrunt.hcl but detected no outputs. Either the target module has not been applied yet, or the module has no outputs. If this is expected, set the skip_outputs flag to true on the dependency block. 
```

to fix this, I added `dev/vpc/outputs.tf`

```bash
$ cd /tmp/dev/vpc
$ terraform apply # (to add the output)
$ cd /tmp/dev/gke
$ terragrunt plan
No changes. Your infrastructure matches the configuration.
```

so final layout:

```
└── dev
│  ├── gke
│  │   └── terragrunt.hcl
│  │   └── cluster.tf
│  └── vpc
│      └── terragrunt.hcl
│      └── network.tf
│      └── outputs.tf
└── modules
    └── gke
    │   └── main.tf
    │   └── variables.tf
    └── vpc
        └── main.tf
        └── outputs.tf
        └── variables.tf
```

with:

`/dev/gke/terragrunt.hcl`:

```terraform
...

dependency "vpc" {
  config_path = "../vpc"
}

inputs = {
  vpc_id = dependency.vpc.outputs.vpc_id
}
```

`/dev/gke/cluster.tf`:

```terraform
variable "vpc_id" {
  type = string
}

module "gke" {
  source            = "../../modules/gke"
  ....
  network           = var.vpc_id
  ...
}
```
`/dev/vpc/network.tf`:

```terraform
module "vpc" {
  source               = "../../modules/vpc"
  ...
}
```

`dev/vpc/outputs.tf`:

```terraform
output "vpc_id" {
  value = module.vpc.vpc_id
}
```

`modules/vpc/main.tf`:

```terraform
resource "google_compute_network" "vpc_network" {
  ...
}
```

`modules/vpc/outputs.tf`:

```terraform
output "vpc_id" {
  value = google_compute_network.vpc_network.id
}
```

**Comment by protonforest** [comment]
how is this a bug? imagine not being able to create multiple resources at the same time just cause they have dependencies on each other.

**Comment by ares-b** [comment]
> how is this a bug? imagine not being able to create multiple resources at the same time just cause they have dependencies on each other.

I guess that you'd expect it to create the 1st resource and use the output to make the 2nd.
Why would you create a dependency then ? If you have to manage it manually

**Comment by cloudlifter95** [comment]
Hey all
new to the technology and hitting this as part of my experiments. Only an "apply-all" action seem to orchestrate successfully my modules, get the dependent outputs right, and deploy successfully.

the "plan-all" action along with the mocked values also works (given the "plan" action is listed under the mocked commands), however mocking the output after a successful apply is not flagged as a change which would force me to delete the state of the dependency and try again... Far from ideal in production.

**Comment by yhakbar** [comment]
Hey folks,

It seems like this issue has gone stale, and I'm trying to get a sense of any issues that currently exist, if there are any.

The way Terragrunt is designed to handle mocks is that it will only use them if the dependency does not have outputs available.

Once a dependency is applied, mocks should no longer be set. Instead, real outputs should be available from the dependency. You can also force this by setting the commands that are allowed to use mocks, using the appropriate attribute.

Given that context, is anyone able to produce a fixture that demonstrates a reproducible bug? That would mean a public repository with simple Terragrunt code I could clone and reproduce the bug on with on my machine.

**Comment by cloudlifter95** [comment]
Hey there
please find my repo: https://github.com/cloudlifter95/terragrunt-pg/blob/main/account2/readme.md
The problem statement can be found under: https://github.com/cloudlifter95/terragrunt-pg/blob/main/account2/readme.md
extract from problem statement: _Although a dependency is defined between the module account2/queue and a random string generator module under account2/queue/random_pet, the random_pet module is not executed on apply (cd account2/queue && terragrunt apply)._

I hope it helps

**Comment by cloudlifter95** [comment]
@yhakbar a bit more experimentation on my end: 

- "apply-all" orchestrates and applies each dependency successfully, which aligns with the documentation: [Documentation](https://terragrunt.gruntwork.io/docs/getting-started/configuration/#:~:text=Note%20that%20the,all%20apply.)

- however, "plan-all" while building successfully the DAG, shows the outputs of the dependency to be "known after apply"(great!) but the dependent modules are shown to have "no change" (which is wrong). Mocking would not help either under the "plan-all"/"apply-all"/"run-all plan"/"run-all apply" commands.

In a nutshell, from where I stand i'd prefer the "plan-all"/"run-all plan" shows there are expected changes on those dependent modules instead of showing "no change". 

**Trace:**
``` bash
USER:~/Terraform/terragrunt/account2/queue (dev) $ tg plan-all
16:55:35.653 WARN   The `plan-all` command is deprecated and will be removed in a future version. Use `terragrunt run-all plan` instead.
16:55:35.666 INFO   The stack at . will be processed in the following order for command plan:
Group 1
- Module ./random_pet

Group 2
- Module .

16:55:35.985 STDOUT [random_pet] terraform: random_pet.this: Refreshing state... [id=jaybird]
16:55:35.990 STDOUT [random_pet] terraform: Terraform used the selected providers to generate the following execution
16:55:35.990 STDOUT [random_pet] terraform: plan. Resource actions are indicated with the following symbols:
16:55:35.990 STDOUT [random_pet] terraform: -/+ destroy and then create replacement
16:55:35.990 STDOUT [random_pet] terraform: Terraform will perform the following actions:
16:55:35.990 STDOUT [random_pet] terraform:   # random_pet.this must be replaced
16:55:35.990 STDOUT [random_pet] terraform: -/+ resource "random_pet" "this" {
16:55:35.990 STDOUT [random_pet] terraform:       ~ id        = "jaybird" -> (known after apply)
16:55:35.990 STDOUT [random_pet] terraform:       ~ keepers   = { # forces replacement
16:55:35.990 STDOUT [random_pet] terraform:           ~ "uuid" = "8ca1795e-bec3-3e58-51ea-7e37ca67e887" -> (known after apply)
16:55:35.990 STDOUT [random_pet] terraform:         }
16:55:35.990 STDOUT [random_pet] terraform:         # (2 unchanged attributes hidden)
16:55:35.990 STDOUT [random_pet] terraform:     }
16:55:35.990 STDOUT [random_pet] terraform: Plan: 1 to add, 0 to change, 1 to destroy.
16:55:35.990 STDOUT [random_pet] terraform:
16:55:35.990 STDOUT [random_pet] terraform: Changes to Outputs:
16:55:35.990 STDOUT [random_pet] terraform:   ~ random_string = "jaybird" -> (known after apply)
16:55:35.990 STDOUT [random_pet] terraform:
16:55:35.990 STDOUT [random_pet] terraform: ─────────────────────────────────────────────────────────────────────────────
16:55:35.991 STDOUT [random_pet] terraform: Note: You didn't use the -out option to save this plan, so Terraform can't
16:55:35.991 STDOUT [random_pet] terraform: guarantee to take exactly these actions if you run "terraform apply" now.
16:55:36.217 INFO   Executing hook: before_hook
16:55:36.221 INFO   Executing hook: before_hook
16:55:37.018 INFO   Executing hook: before_hook
16:55:39.707 STDOUT terraform: data.aws_region.current: Reading...
16:55:39.707 STDOUT terraform: data.aws_caller_identity.current: Reading...
16:55:39.708 STDOUT terraform: data.aws_region.current: Read complete after 0s [id=eu-central-1]
16:55:39.708 STDOUT terraform: aws_sqs_queue.this[0]: Refreshing state... [id=https://sqs.eu-central-1.amazonaws.com/****/jaybird]
16:55:39.735 STDOUT terraform: data.aws_caller_identity.current: Read complete after 0s [id=****]
16:55:40.180 STDOUT terraform: No changes. Your infrastructure matches the configuration.
16:55:40.180 STDOUT terraform: Terraform has compared your real infrastructure against your configuration
16:55:40.180 STDOUT terraform: and found no differences, so no changes are needed.
16:55:40.182 INFO   Executing hook: after_hook
16:55:40.185 INFO   Executing hook: after_hook
Running Terragrunt
{
    "UserId": "***",
    "Account": "****",
    "Arn": "arn:aws:iam::****:user/***"
}
testglobalinput
Finished running Terragrunt
testglobalinput
USER:~/Terraform/terragrunt/account2/queue (dev) $ tg apply-all
16:56:47.975 WARN   The `apply-all` command is deprecated and will be removed in a future version. Use `terragrunt run-all apply` instead.
16:56:48.002 INFO   The stack at . will be processed in the following order for command apply:
Group 1
- Module ./random_pet

Group 2
- Module .

Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n) y
16:56:49.837 STDOUT [random_pet] terraform: random_pet.this: Refreshing state... [id=jaybird]
16:56:49.842 STDOUT [random_pet] terraform: Terraform used the selected providers to generate the following execution
16:56:49.842 STDOUT [random_pet] terraform: plan. Resource actions are indicated with the following symbols:
16:56:49.843 STDOUT [random_pet] terraform: -/+ destroy and then create replacement
16:56:49.843 STDOUT [random_pet] terraform: Terraform will perform the following actions:
16:56:49.843 STDOUT [random_pet] terraform:   # random_pet.this must be replaced
16:56:49.843 STDOUT [random_pet] terraform: -/+ resource "random_pet" "this" {
16:56:49.843 STDOUT [random_pet] terraform:       ~ id        = "jaybird" -> (known after apply)
16:56:49.843 STDOUT [random_pet] terraform:       ~ keepers   = { # forces replacement
16:56:49.843 STDOUT [random_pet] terraform:           ~ "uuid" = "8ca1795e-bec3-3e58-51ea-7e37ca67e887" -> (known after apply)
16:56:49.843 STDOUT [random_pet] terraform:         }
16:56:49.843 STDOUT [random_pet] terraform:         # (2 unchanged attributes hidden)
16:56:49.843 STDOUT [random_pet] terraform:     }
16:56:49.843 STDOUT [random_pet] terraform: Plan: 1 to add, 0 to change, 1 to destroy.
16:56:49.843 STDOUT [random_pet] terraform:
16:56:49.843 STDOUT [random_pet] terraform: Changes to Outputs:
16:56:49.843 STDOUT [random_pet] terraform:   ~ random_string = "jaybird" -> (known after apply)
16:56:49.885 STDOUT [random_pet] terraform: random_pet.this: Destroying... [id=jaybird]
16:56:49.887 STDOUT [random_pet] terraform: random_pet.this: Destruction complete after 0s
16:56:49.898 STDOUT [random_pet] terraform: random_pet.this: Creating...
16:56:49.898 STDOUT [random_pet] terraform: random_pet.this: Creation complete after 0s [id=hare]
16:56:49.912 STDOUT [random_pet] terraform:
16:56:49.912 STDOUT [random_pet] terraform: Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
16:56:49.912 STDOUT [random_pet] terraform:
16:56:49.912 STDOUT [random_pet] terraform: Outputs:
16:56:49.912 STDOUT [random_pet] terraform: random_string = "hare"
16:56:51.084 INFO   Executing hook: before_hook
16:56:51.226 INFO   Executing hook: before_hook
16:56:53.348 INFO   Executing hook: before_hook
16:56:56.897 STDOUT terraform: data.aws_region.current: Reading...
16:56:56.897 STDOUT terraform: data.aws_caller_identity.current: Reading...
16:56:56.898 STDOUT terraform: aws_sqs_queue.this[0]: Refreshing state... [id=https://sqs.eu-central-1.amazonaws.com/****/jaybird]
16:56:56.899 STDOUT terraform: data.aws_region.current: Read complete after 0s [id=eu-central-1]
16:56:56.935 STDOUT terraform: data.aws_caller_identity.current: Read complete after 0s [id=****]
16:56:57.393 STDOUT terraform: Terraform used the selected providers to generate the following execution
16:56:57.393 STDOUT terraform: plan. Resource actions are indicated with the following symbols:
16:56:57.393 STDOUT terraform: -/+ destroy and then create replacement
16:56:57.393 STDOUT terraform: Terraform will perform the following actions:
16:56:57.393 STDOUT terraform:   # aws_sqs_queue.this[0] must be replaced
16:56:57.393 STDOUT terraform: -/+ resource "aws_sqs_queue" "this" {
16:56:57.393 STDOUT terraform:       ~ arn                               = "arn:aws:sqs:eu-central-1:****:jaybird" -> (known after apply)
16:56:57.393 STDOUT terraform:       + deduplication_scope               = (known after apply)
16:56:57.393 STDOUT terraform:       + fifo_throughput_limit             = (known after apply)
16:56:57.393 STDOUT terraform:       ~ id                                = "https://sqs.eu-central-1.amazonaws.com/****/jaybird" -> (known after apply)
16:56:57.393 STDOUT terraform:       ~ kms_data_key_reuse_period_seconds = 300 -> (known after apply)
16:56:57.394 STDOUT terraform:       ~ name                              = "jaybird" -> "hare" # forces replacement
16:56:57.394 STDOUT terraform:       + name_prefix                       = (known after apply)
16:56:57.394 STDOUT terraform:       + policy                            = (known after apply)
16:56:57.394 STDOUT terraform:       + redrive_allow_policy              = (known after apply)
16:56:57.394 STDOUT terraform:       + redrive_policy                    = (known after apply)
16:56:57.394 STDOUT terraform:         tags                              = {
16:56:57.394 STDOUT terraform:             "Account"     = "account2"
16:56:57.394 STDOUT terraform:             "Environment" = "dev"
16:56:57.394 STDOUT terraform:             "IAC"         = "true"
16:56:57.394 STDOUT terraform:             "globaltag"   = "testglobalinput"
16:56:57.394 STDOUT terraform:         }
16:56:57.394 STDOUT terraform:       ~ url                               = "https://sqs.eu-central-1.amazonaws.com/****/jaybird" -> (known after apply)
16:56:57.394 STDOUT terraform:         # (9 unchanged attributes hidden)
16:56:57.394 STDOUT terraform:     }
16:56:57.394 STDOUT terraform: Plan: 1 to add, 0 to change, 1 to destroy.
16:56:57.394 STDOUT terraform:
16:56:57.394 STDOUT terraform: Changes to Outputs:
16:56:57.395 STDOUT terraform:   ~ queue_arn                    = "arn:aws:sqs:eu-central-1:****:jaybird" -> (known after apply)
16:56:57.395 STDOUT terraform:   ~ queue_arn_static             = "arn:aws:sqs:eu-central-1:****:jaybird" -> "arn:aws:sqs:eu-central-1:****:hare"
16:56:57.395 STDOUT terraform:   ~ queue_id                     = "https://sqs.eu-central-1.amazonaws.com/****/jaybird" -> (known after apply)
16:56:57.395 STDOUT terraform:   ~ queue_name                   = "jaybird" -> "hare"
16:56:57.395 STDOUT terraform:   ~ queue_url                    = "https://sqs.eu-central-1.amazonaws.com/****/jaybird" -> (known after apply)
16:56:58.460 STDOUT terraform: aws_sqs_queue.this[0]: Destroying... [id=https://sqs.eu-central-1.amazonaws.com/****/jaybird]
16:57:00.719 STDOUT terraform: aws_sqs_queue.this[0]: Destruction complete after 3s
16:57:00.733 STDOUT terraform: aws_sqs_queue.this[0]: Creating...
16:57:10.736 STDOUT terraform: aws_sqs_queue.this[0]: Still creating... [10s elapsed]
16:57:20.737 STDOUT terraform: aws_sqs_queue.this[0]: Still creating... [20s elapsed]
16:57:26.186 STDOUT terraform: aws_sqs_queue.this[0]: Creation complete after 25s [id=https://sqs.eu-central-1.amazonaws.com/****/hare]
16:57:26.205 STDOUT terraform:
16:57:26.205 STDOUT terraform: Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
16:57:26.205 STDOUT terraform:
16:57:26.205 STDOUT terraform: Outputs:
16:57:26.205 STDOUT terraform: dead_letter_queue_arn_static = ""
16:57:26.205 STDOUT terraform: queue_arn = "arn:aws:sqs:eu-central-1:****:hare"
16:57:26.206 STDOUT terraform: queue_arn_static = "arn:aws:sqs:eu-central-1:****:hare"
16:57:26.206 STDOUT terraform: queue_id = "https://sqs.eu-central-1.amazonaws.com/****/hare"
16:57:26.206 STDOUT terraform: queue_name = "hare"
16:57:26.206 STDOUT terraform: queue_url = "https://sqs.eu-central-1.amazonaws.com/****/hare"
16:57:26.210 INFO   Executing hook: after_hook
16:57:26.238 INFO   Executing hook: after_hook
Running Terragrunt
{
    "UserId": "***",
    "Account": "****",
    "Arn": "arn:aws:iam::****:user/***"
}
testglobalinput
Finished running Terragrunt
testglobalinput
USER:~/Terraform/terragrunt/account2/queue (dev) $
```

**Comment by manku211** [comment]
is this will be solved or not ?

**Comment by agu627** [comment]
hello guys, can i join the fun?

**Comment by yhakbar** [comment]
Hey folks. I skimmed over the fixture provided by @cloudlifter95 [here](https://github.com/cloudlifter95/terragrunt-pg/tree/main/account2) (thanks for that, btw. It really helped me a lot).

I think what might be causing an issue there is that folks might expect dependencies to be automatically applied when running `terragrunt apply` in a dependent. That's only going to happen when using commands like `terragrunt run-all apply` and allowing Terragrunt to pull from external dependencies.

At a high-level, I want to make sure that folks are using Terragrunt as intended, and not trying to make Terragrunt fit into a pattern that it wasn't designed for. To that end, I would recommend that anyone that hasn't read the [Getting Started Guide](https://terragrunt.gruntwork.io/docs/#getting-started), then try to give a simple explanation of what standard use-cases aren't supported by Terragrunt, and why they're important to your team. To be clear, I'm not saying that the folks here _are_ using Terragrunt in this way, I'm just trying to understand the issue better so that I can understand how using Terragrunt as intended is causing these issues.

Terragrunt will fetch the outputs of dependencies, so I don't think this issue is appropriately named. Naming it something more accurate might help us, as the maintainers get a better understanding of what the underlying problem is. The description is also referencing a very old version of Terragrunt, and has a typo in the configurations, so if that could be updated, that would be great.

**Comment by Dessix** [comment]
It's possible that the intended use is not what others interpreted it to be- I certainly assumed that dependencies would be fulfilled on-demand if I tried to perform an action which consumed them - like Nix would - and saw this is a key, motivating feature for use.

**Comment by yhakbar** [comment]
So, there are ways to make that happen, but the ability to avoid doing that is part of what makes Terragrunt special. You can reduce the blast radius of infrastructure changes by only updating one unit of infrastructure at a time.

There's a dedicated `run-all` command which _does_ signal to dependencies that they need to be updated too, and they'll be updated in accordance with their position within the [DAG](https://terragrunt.gruntwork.io/docs/getting-started/terminology/#directed-acyclic-graph-dag), but you opt-in to that when you want to increase your blast radius because you want to update multiple independent pieces of infrastructure at once. You can learn more about that [here](https://terragrunt.gruntwork.io/docs/features/stacks/#the-run-all-command).

**Comment by idkman23** [comment]
@yhakbar I'm facing a similar issue when running `tg run-all  apply --queue-include-external` 
Example from the `keycloak` directory:

keycloak/
├── deployment
│   └── terragrunt.hcl
├── initial-config
│   └── terragrunt.hcl


**initial-config/terragrunt.hcl**
```
dependency "keycloak_deployment" {
   config_path = "${get_terragrunt_dir()}/../deployment"
   mock_outputs = {
     keycloak_url      = "test.io"
     keycloak_password = "dafdsfas"
   }
}

inputs = {
    keycloak_url             = format("%s%s", "https://", dependency.keycloak_deployment.outputs.keycloak_url)
    keycloak_password = dependency.keycloak_deployment.outputs.keycloak_password
}
```

```
deployment] terraform: helm_release.keycloak: Still creating... [2m30s elapsed]
17:20:39.629 STDOUT [deployment] terraform: helm_release.keycloak: Still creating... [2m40s elapsed]
17:20:46.887 STDOUT [deployment] terraform: helm_release.keycloak: Creation complete after 2m47s [id=keycloak]
17:20:47.904 STDOUT [deployment] terraform: 
17:20:47.904 STDOUT [deployment] terraform: Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
17:20:47.904 STDOUT [deployment] terraform: 
17:20:47.904 STDOUT [deployment] terraform: Outputs:
17:20:47.904 STDOUT [deployment] terraform: keycloak_password = <sensitive>
17:20:47.904 STDOUT [deployment] terraform: keycloak_url = "auth.platform.io"
17:20:48.168 WARN   [initial-config] Config ./deployment/terragrunt.hcl is a dependency of ./initial-config/terragrunt.hcl that has no outputs, but mock outputs provided and returning those in dependency output.
17:20:50.204 STDERR [initial-config] terraform: ╷
17:20:50.204 STDERR [initial-config] terraform: │ Error: error initializing keycloak provider
17:20:50.204 STDERR [initial-config] terraform: │ 
17:20:50.205 STDERR [initial-config] terraform: │   with provider["registry.terraform.io/mrparkers/keycloak"],
17:20:50.205 STDERR [initial-config] terraform: │   on providers.tf line 1, in provider "keycloak":
17:20:50.205 STDERR [initial-config] terraform: │    1: provider "keycloak" {
17:20:50.205 STDERR [initial-config] terraform: │ 
17:20:50.205 STDERR [initial-config] terraform: │ failed to perform initial login to Keycloak: error sending POST request to
17:20:50.206 STDERR [initial-config] terraform: │ https://test.io/auth/realms/master/protocol/openid-connect/token: 403
17:20:50.206 STDERR [initial-config] terraform: │ Forbidden
```
Take note of the `WARN` statement. The outputs are created right before the warn statement, yet it uses the mock_outputs (`test.io`) and fails on the next step.

If I run the `run-all` command again, it recognizes the real outputs and succeds.

**Comment by socketbox** [comment]
> The issue occurred for us after updating from terraform `0.13` to `0.15` and terragrunt from `0.23` to `0.29`.
> 
> 👉 We could **fix the issue** by deleting the `.terraform` directory in the dependend project. Now it works even without `disable_dependency_optimization = true`.
> 
> This might also explain why [@yorinasub17](https://github.com/yorinasub17) could not reproduce the issue.

This is what caused problems for me as well. The presence of a `.terraform` directory in the dependency seems to prompt Terragrunt to run `terraform output -json`. But this generates an empty object. Remote state is managed by Terragrunt and in a `remote_state` block within `terragrunt.hcl`, so I suspect that `terragrunt output -json` should be used. When I removed the `.terraform` directory, removed `.terragrunt-cache` and re-inited the dependency, everything worked smoothly.

@czenker 🥇 


Update: out of the blue, ten minutes after having successfully run (though not completed due to unrelated errors) `tg apply`, I received this error when running `tg plan`. I'd made no changes to the dependency's module:
(**nevermind**: this was due to lapsed, ephemeral AWS credentials)
```

[origin RWEB-9364-refactor-staging][𝕐 default][🅰 pbs-digi-preprod][preprod-staging/live/staging]
[2025-08-04 18:30:13]» tg plan
╷
│ Error: Backend initialization required, please run "terraform init"
│
│ Reason: Initial configuration of the requested backend "s3"
│
│ The "backend" is the interface that Terraform uses to store state,
│ perform operations, etc. If this message is showing up, it means that the
│ Terraform configuration you're using is using a custom configuration for
│ the Terraform backend.
│
│ Changes to backend configurations require reinitialization. This allows
│ Terraform to set up the new configuration, copy existing state, etc. Please
│ run
│ "terraform init" with either the "-reconfigure" or "-migrate-state" flags
│ to
│ use the current configuration.
│
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
╵
18:39:32.933 ERROR  Error: Unknown variable
18:39:32.933 ERROR    on ./terragrunt.hcl line 161:
...
18:39:32.973 ERROR  Error: Unknown variable
18:39:32.973 ERROR    on ./terragrunt.hcl line 195:
18:39:32.975 ERROR   195:       bgjobs_image_repo_url = dependency.external.outputs.pbsorg_next_bgjobs_image_repository_url
18:39:32.975 ERROR  There is no variable named "dependency".
18:39:32.978 ERROR  2 errors occurred:

* Failed to execute "terraform output -json" in ../../external/.terragrunt-cache/3712671775
  ╷
  │ Error: Backend initialization required, please run "terraform init"
  │
  │ Reason: Initial configuration of the requested backend "s3"
  │
  │ The "backend" is the interface that Terraform uses to store state,
  │ perform operations, etc. If this message is showing up, it means that the
  │ Terraform configuration you're using is using a custom configuration for
  │ the Terraform backend.
  │
  │ Changes to backend configurations require reinitialization. This allows
  │ Terraform to set up the new configuration, copy existing state, etc. Please
  │ run
  │ "terraform init" with either the "-reconfigure" or "-migrate-state" flags
  │ to
  │ use the current configuration.
  │
  │ If the change reason above is incorrect, please verify your configuration
  │ hasn't changed and try again. At this point, no changes to your existing
  │ configuration or state have been made.
  ╵

  exit status 1

* ./terragrunt.hcl:161,49-59: Unknown variable; There is no variable named "dependency"., and 16 other diagnostic(s)

[origin RWEB-9364-refactor-staging][𝕐 default][🅰 pbs-digi-preprod][preprod-staging/live/staging]
[2025-08-04 18:40:57]❮
```

Hah. The error shown in the *Update* was due to lapsed ephemeral AWS credentials.

**Comment by yhakbar** [comment]
Hey folks!

We need to get more clarity on reproducibility if we're going to address this. That means complete configurations and step-by-step instructions on how to reproduce the issues that you're facing. I know it's annoying, but it's the only way we can guarantee that we've addressed the issue and have testing to avoid regression in the bug you all are seeing.

If you need help with setting up a fixture or are uncomfortable sharing code because you're worried you might accidentally share something sensitive, feel free to DM me in the Terragrunt Discord (especially you, @socketbox . I haven't spoken to you in too long).

**Comment by yld** [comment]
I could reproduce the problematic behavior playing with environment variables (using `mise` but other solutions should work too).

Given the following structure:
```
/ 
  mise.toml
  shared/
     mise.toml
     organisation/
       terragrunt.hcl
     repository/
       terragrunt.hcl
```

 With /mise.toml containing:

```toml
[env]
TF_DATA_DIR = "{{config_root}}/.terraform"
TF_IGNORE = "trace"
TF_LOG = "off"
TG_DOWNLOAD_DIR = "{{config_root}}/.terragrunt/downloads"
TG_PROVIDER_CACHE = 1
TG_PROVIDER_CACHE_DIR = "{{config_root}}/.terragrunt/provider-cache"
```

And /shared/mise.toml containing:
```toml
[env]
TF_DATA_DIR = "{{config_root}}/.terraform"
TF_LOG = "off"
```

Terraform module in /shared/organisation/terragrunt.hcl was outputing values.

Those values are used through a dependency in /shared/repository/terragrunt.hcl 

So i could `apply` successfully into /shared/organisation but i was told that dependency was not defined while running any command from within /shared/repository.

Going back to /shared/organisation i had to `init` again and again without success.

Removing all the `TF_*` and `TG_*` custom environment variables solved the problem.

Same behavior with `terraform` and `opentofu`.

Hope this helps...

**Comment by yhakbar** [comment]
Hey folks, 

This issue has gotten stale, and I'm not sure there's an actionable, reproducible bug to tackle here.

If you are currently experiencing any bugs with Terragrunt, please consider creating a new bug report with detailed reproduction steps to maximize the likelihood that maintainers are able to resolve the bug. I'm going to close this issue out.
