### ISSUE TITLE
run-all plan runs init twice on the same module

### ISSUE THREAD

**Issue by thisispaulsmith** [gruntwork-io/terragrunt#2519]
Running 

```
terragrunt run-all plan
```

results in `init` being called twice, once at the start and then again after running the plan.

I've tried the latest and a couple of previous versions. My sample is very simple.

Anything that would cause this?

Log output below...

```
PS C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg> terragrunt run-all plan --terragrunt-log-level debug --terragrunt-debug
time=2023-04-06T08:02:12+01:00 level=debug msg=Did not find any locals block: skipping evaluation. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Detected single bare include block - exposing as top level prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Detected single bare include block - exposing as top level prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Detected single bare include block - exposing as top level prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Found locals block: evaluating the expressions. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Evaluated 1 locals (remaining 0): subscription_id prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=[Partial] Included config C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/terragrunt.hcl has strategy shallow merge: merging config in (shallow). prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Setting download directory for module C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg to C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache
time=2023-04-06T08:02:12+01:00 level=debug msg=Stack at C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg:
  => Module C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg (excluded: false, assume applied: false, dependencies: [])
time=2023-04-06T08:02:12+01:00 level=info msg=The stack at C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg will be processed in the following order for command plan:
Group 1
- Module C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg


time=2023-04-06T08:02:12+01:00 level=debug msg=Module C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg must wait for 0 dependencies to finish prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Running module C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg now prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Did not find any locals block: skipping evaluation. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Detected single bare include block - exposing as top level prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Found locals block: evaluating the expressions. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Evaluated 1 locals (remaining 0): subscription_id prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=[Partial] Included config C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/terragrunt.hcl has strategy shallow merge: merging config in (shallow). prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Running command: terraform --version prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Terraform version: 1.4.4 prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Reading Terragrunt config file at C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/terragrunt.hcl prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Did not find any locals block: skipping evaluation. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Detected single bare include block - exposing as top level prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Found locals block: evaluating the expressions. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Evaluated 1 locals (remaining 0): subscription_id prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=[Partial] Included config C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/terragrunt.hcl has strategy shallow merge: merging config in (shallow). prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Did not find any locals block: skipping evaluation. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Detected single bare include block - exposing as top level prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Found locals block: evaluating the expressions. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Evaluated 1 locals (remaining 0): subscription_id prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Included config C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/terragrunt.hcl has strategy shallow merge: merging config in (shallow) for dependency. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Detected single bare include block - exposing as top level prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Found locals block: evaluating the expressions. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Evaluated 1 locals (remaining 0): subscription_id prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Found locals block: evaluating the expressions. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Evaluated 1 locals (remaining 0): subscription_id prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Included config C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/terragrunt.hcl has strategy shallow merge: merging config in (shallow). prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Downloading Terraform configurations from file://C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/modules into C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache/JIgFn6BPKOh3rQfg7rgbUpzb3NA/6i22O9zNwcBMrF5SQ1B4DAcLS5Q prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Copying files from C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg into C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache/JIgFn6BPKOh3rQfg7rgbUpzb3NA/6i22O9zNwcBMrF5SQ1B4DAcLS5Q/rg prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Setting working directory to C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache/JIgFn6BPKOh3rQfg7rgbUpzb3NA/6i22O9zNwcBMrF5SQ1B4DAcLS5Q/rg prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Generated file C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg\.terragrunt-cache\JIgFn6BPKOh3rQfg7rgbUpzb3NA\6i22O9zNwcBMrF5SQ1B4DAcLS5Q\rg\versions.tf. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Generated file C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg\.terragrunt-cache\JIgFn6BPKOh3rQfg7rgbUpzb3NA\6i22O9zNwcBMrF5SQ1B4DAcLS5Q\rg\backend.tf. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=info msg=Debug mode requested: generating debug file terragrunt-debug.tfvars.json in working dir C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache/JIgFn6BPKOh3rQfg7rgbUpzb3NA/6i22O9zNwcBMrF5SQ1B4DAcLS5Q/rg prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=The following variables were detected in the terraform module: prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=[] prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Variables passed to terraform are located in "C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg\terragrunt-debug.tfvars.json" prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Run this command to replicate how terraform was invoked: prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg= terraform plan -input=false -var-file="C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg\terragrunt-debug.tfvars.json" "C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache/JIgFn6BPKOh3rQfg7rgbUpzb3NA/6i22O9zNwcBMrF5SQ1B4DAcLS5Q/rg" prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Initializing remote state for the azurerm backend prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Running command: terraform init prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "2.95.0"...
- Installing hashicorp/azurerm v2.95.0...
- Installed hashicorp/azurerm v2.95.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
time=2023-04-06T08:02:24+01:00 level=debug msg=Copying lock file from C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache/JIgFn6BPKOh3rQfg7rgbUpzb3NA/6i22O9zNwcBMrF5SQ1B4DAcLS5Q/rg/.terraform.lock.hcl to C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:24+01:00 level=debug msg=Running command: terraform plan -input=false prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_resource_group.example will be created
  + resource "azurerm_resource_group" "example" {
      + id       = (known after apply)
      + location = "uksouth"
      + name     = "RG-Terragrunt"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
time=2023-04-06T08:02:37+01:00 level=debug msg=Module C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg has finished successfully! prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:37+01:00 level=info msg=time=2023-04-06T08:02:12+01:00 level=debug msg=Running command: terraform --version prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Generated file C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg\.terragrunt-cache\JIgFn6BPKOh3rQfg7rgbUpzb3NA\6i22O9zNwcBMrF5SQ1B4DAcLS5Q\rg\versions.tf. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Generated file C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg\.terragrunt-cache\JIgFn6BPKOh3rQfg7rgbUpzb3NA\6i22O9zNwcBMrF5SQ1B4DAcLS5Q\rg\backend.tf. prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=info msg=Debug mode requested: generating debug file terragrunt-debug.tfvars.json in working dir C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache/JIgFn6BPKOh3rQfg7rgbUpzb3NA/6i22O9zNwcBMrF5SQ1B4DAcLS5Q/rg prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=The following variables were detected in the terraform module: prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=[] prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Variables passed to terraform are located in "C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg\terragrunt-debug.tfvars.json" prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Run this command to replicate how terraform was invoked: prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg= terraform plan -input=false -var-file="C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg\terragrunt-debug.tfvars.json" "C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache/JIgFn6BPKOh3rQfg7rgbUpzb3NA/6i22O9zNwcBMrF5SQ1B4DAcLS5Q/rg" prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Initializing remote state for the azurerm backend prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:12+01:00 level=debug msg=Running command: terraform init prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "2.95.0"...
- Installing hashicorp/azurerm v2.95.0...
- Installed hashicorp/azurerm v2.95.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
time=2023-04-06T08:02:24+01:00 level=debug msg=Copying lock file from C:/Users/PaulSmith/source/repos/Terragrunt/infrastructure/environments/QA/primary/rg/.terragrunt-cache/JIgFn6BPKOh3rQfg7rgbUpzb3NA/6i22O9zNwcBMrF5SQ1B4DAcLS5Q/rg/.terraform.lock.hcl to C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
time=2023-04-06T08:02:24+01:00 level=debug msg=Running command: terraform plan -input=false prefix=[C:\Users\PaulSmith\source\repos\Terragrunt\infrastructure\environments\QA\primary\rg]
```

**Comment by thisispaulsmith** [comment]
The second `init` fails on build agents in Azure DevOps though it success locally. I can't work out why my guess is credentials aren't being set.

**Comment by levkoburburas** [comment]
@thisispaulsmith, In fact, `terraform init` is only run once, but this output is displayed twice. The bug is only in the display and fixed in #2557

**Comment by thisispaulsmith** [comment]
@levkoburburas This problem still persists running v0.45.10

**Comment by levkoburburas** [comment]
> @levkoburburas This problem still persists running v0.45.10. It doesn't look like a double init but it's writing duplicate logs to stderr.

@thisispaulsmith the fixed code was merged to master branch but the release with fixes has not been issued yet.

**Comment by thisispaulsmith** [comment]
@levkoburburas OK. However, the release notes include #2558 as being included?

**Comment by thisispaulsmith** [comment]
I still get duplicate log entries, one as a normal log and one as StdErr.

Example (with stuff removed for berevity)

```
terragrunt version v0.45.10
############################################################
RUNNING 'terragrunt plan --terragrunt-non-interactive'
############################################################
**time=2023-05-10T11:17:37Z level=info msg=The stack at /azp/_work/1/s/infrastructure/Azure/terraform/environments/QA/mono will be processed in the following order for command** plan:
Group 1
- Module /azp/_work/1/s/infrastructure/Azure/terraform/environments/QA/mono



Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...

[REMOVED]

Initializing provider plugins...
- Finding hashicorp/azuread versions matching "~> 2.36.0"...
- Finding hashicorp/random versions matching "~> 3.1"...
- Finding latest version of hashicorp/time...
- Finding latest version of hashicorp/helm...
- Finding latest version of hashicorp/kubernetes...
- Finding hashicorp/azurerm versions matching "~> 3.48.0"...
- Installing hashicorp/time v0.9.1...
- Installed hashicorp/time v0.9.1 (signed by HashiCorp)
- Installing hashicorp/helm v2.9.0...
- Installed hashicorp/helm v2.9.0 (signed by HashiCorp)
- Installing hashicorp/kubernetes v2.20.0...
- Installed hashicorp/kubernetes v2.20.0 (signed by HashiCorp)
- Installing hashicorp/azurerm v3.48.0...
- Installed hashicorp/azurerm v3.48.0 (signed by HashiCorp)
- Installing hashicorp/azuread v2.36.0...
- Installed hashicorp/azuread v2.36.0 (signed by HashiCorp)
- Installing hashicorp/random v3.5.1...
- Installed hashicorp/random v3.5.1 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

[REMOVED]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
##[error]time=2023-05-10T11:17:37Z level=info msg=The stack at /azp/_work/1/s/infrastructure/Azure/terraform/environments/QA/mono will be processed in the following order for command plan:
Group 1
- Module /azp/_work/1/s/infrastructure/Azure/terraform/environments/QA/mono


##[error]Script has output to stderr. Failing as failOnStdErr is set to true.

```

**Comment by levkoburburas** [comment]
@thisispaulsmith, thank you for the log, now I see what you mean. Could you please create a new issue with the same description?
